export interface KanbanJob {
  id: number;
  jobNumber: string;
  title: string;
  stageName: string;
  stageColor: string;
  assigneeId: number | null;
  assigneeInitials: string | null;
  assigneeColor: string | null;
  priorityName: string;
  dueDate: Date | null;
  isOverdue: boolean;
  customerName: string | null;
  customerId: number | null;
  salesOrderId: number | null;
  salesOrderNumber: string | null;
  billingStatus: string | null;
  externalRef: string | null;
  accountingDocumentType: string | null;
  disposition: string | null;
  childJobCount: number;
  activeHolds: string[];
  coverPhotoUrl: string | null;
  parentJobId: number | null;
  parentJobNumber: string | null;
  boardPosition: number;
  partNumber: string | null;
  quantity: number | null;
  completedDate?: string | null;
  operationsTotal?: number | null;
  operationsComplete?: number | null;
  inProgressSteps?: number[] | null;
  runningTimerCount?: number | null;
  estimatedRemainingMinutes?: number | null;
}
